# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Occupational Hazard
email:
description: >- # this means to ignore newlines until "baseurl:"
  Tamas Santa's personal blog about engineering practices, technologies and advantures in the cloud.
twitter_username: TamasSanta
github_username: santatamas
minimal_mistakes_skin: dark
search: true
logo: "assets/images/logo.png"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Tamas Santa"
  avatar : "/assets/images/avatar.jpeg"
  bio    : "**Solutions Architect @ AWS** - Dad of 2 kittens."
  location : "Leeds, United Kingdom"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://blog.tamas-santa.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/TamasSanta"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/santatamas"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/santatamas/"

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-83049324-1

footer:
   links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://blog.tamas-santa.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/TamasSanta"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/santatamas"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/santatamas/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-83049324-1"
    anonymize_ip: false # default

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
